### PR TITLE
Just a small cleanup & Versions update

### PR DESCRIPTION
**Pull request by saikek**
It would be good if you can place some widgets on the readme file to see 
`build status`, `current version`, `libraries version`, `license`, etc.

Updated versions of components manually to the latest one (according to VersionEye).

### CODE REVIEW

**Comment by aimmac23** [comment]
Hi saikek,

Thanks for the pull request - I'll take a look over the weekend.

Thanks,

Alasdair

**Comment by aimmac23** [comment]
Looks good.

I have a Jenkins instance which can do build status - do you know of any internet guide for making it do the current released version?

**Comment by saikek** [comment]
I haven't found one that would have all instructions - i will try to create it on my branch and will let you merge back with yours.

**Comment by saikek** [comment]
So just a few that i recommend:
[from shields](https://shields.io/)

Release version: Version
License version: [License]

Register on Travis.ci, create `.travis.yml` file and add badge for CI.
Register on `versioneye.com` and add badge for components versions.
Register on `codecov.io` and add code coverage badge.
Register on `api.codacy.com` for code style badge.
Also might be interesting to add analytics badge to see visits for the page, at `https://ga-beacon.appspot.com`

You can add me to the team for README page update, and i can help with this one.

**Comment by saikek** [comment]
^ you need for most of the badges to access you repository. All of tools are free for open-source projects.

**Pull request merged**
